-- 코드를 입력하세요
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME FROM ANIMAL_INS
WHERE (SEX_UPON_INTAKE = "Intact Male" OR SEX_UPON_INTAKE = "Intact Female") AND SEX_UPON_INTAKE !=
    (SELECT SEX_UPON_OUTCOME FROM ANIMAL_OUTS
    WHERE ANIMAL_ID = ANIMAL_INS.ANIMAL_ID)